version: "3.8"

services:
  browsy-server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    ports:
      - "3100:3100"
      - "3325:3325"
    volumes:
      - browsy_data:/app/data
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - PORT=3100
      - MCP_PORT=3325
      - NODE_ENV=production
      - DISPLAY=${DISPLAY}
    networks:
      - browsy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  browsy-nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - browsy-server
    networks:
      - browsy-network
    restart: unless-stopped

volumes:
  browsy_data:
    driver: local

networks:
  browsy-network:
    driver: bridge
